GRANT USAGE ON SCHEMA lystore TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA lystore TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA lystore TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA lystore TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA lystore GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA lystore GRANT EXECUTE ON FUNCTIONS TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA lystore GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "apps";
